; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:tracker]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<*> -<beacon.cpp>
; build_flags =
;   -D BLESERIAL_USE_NIMBLE=true
lib_deps =
	mikalhart/TinyGPSPlus@^1.0.3
        senseshift/Serial_BLE
        h2zero/NimBLE-Arduino@^1.4.0
        etlcpp/Embedded Template Library@^20.46.2


[env:beacon]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<*> -<tracker.cpp>
lib_deps =
	mikalhart/TinyGPSPlus@^1.0.3
        h2zero/NimBLE-Arduino@^1.4.0
